### ISSUE TITLE
Xubuntu 20.04 and Gmusicbrowser cloned from this repo: compilation aborted at ./gmusicbrowser.pl line 473.

### ISSUE THREAD

**Issue by gordqalk** [squentin/gmusicbrowser#172]
Gmusicbrowser worked under Xubuntu 19.10 but after upgrading to 20.04 I cannot run it. If I execute `./gmusicbrowser.pl` I get:

`Can't redeclare "my" in "my" at /home/sherman/Compiled/gmusicbrowser-1.1.15/gmusicbrowser_list.pm line 8001, near ",my"
Compilation failed in require at ./gmusicbrowser.pl line 440.
BEGIN failed--compilation aborted at ./gmusicbrowser.pl line 473.
`
thanks

**Comment by squentin** [comment]
Yes sorry, it's an old bug but I haven't made a proper release for far far too long. You should use the latest from git, From the branch 1.1.x (https://github.com/squentin/gmusicbrowser/tree/v1.1.x) if you want gtk2 or from master if you want the new beta using gtk3.
